version: '2'

services:
  namesrv:
    build: .
    container_name: rmqnamesrv
    ports:
      - 9876:9876
      - 10012:10010
    environment:
      - JAVA_OPT_EXT=-Xms1g -Xmx1g -Xmn512m
      - JAVA_OPT=-Xdebug -Xrunjdwp:transport=dt_socket,address=10010,server=y,suspend=n
    command: sh mqnamesrv

  broker:
    build: .
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
      - 10011:10010
    environment:
      - JAVA_OPT_EXT=-Xms1g -Xmx1g -Xmn512m
      - JAVA_OPT=-Xdebug -Xrunjdwp:transport=dt_socket,address=10010,server=y,suspend=n
    command: sh mqbroker -n namesrv:9876 -c ../conf/broker.conf
    depends_on:
      - namesrv

  dashboard:
    image: apacherocketmq/rocketmq-dashboard
    container_name: rmqdashboard
    restart: always
    ports:
      - 8080:8080
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=namesrv:9876"
    depends_on:
      - namesrv

  test:
    build: .
    container_name: rmq_test
    environment:
      - JAVA_OPT_EXT=-Xms1g -Xmx1g -Xmn512m
    command: tail -f