version: '2'

services:
  namesrv:
      image: apache/rocketmq:4.9.4
      container_name: rmqnamesrv
      ports:
        - 9876:9876
        - 9555:9555
      environment:
        JAVA_OPT: "-Xdebug -Xrunjdwp:transport=dt_socket,address=9555,server=y,suspend=n"
      command: sh mqnamesrv

  broker:
    image: apache/rocketmq:4.9.4
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
      - 9556:9555
    environment:
        JAVA_OPT: "-Xdebug -Xrunjdwp:transport=dt_socket,address=9555,server=y,suspend=n"
    command: sh mqbroker -n namesrv:9876 -c ../conf/broker.conf
    depends_on:
      - namesrv


  dashboard:
    image: apacherocketmq/rocketmq-dashboard
    container_name: rmqdashboard
    restart: always
    ports:
      - 8081:8081
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=namesrv:9876"
    depends_on:
      - namesrv
